//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disco_STU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiscoSTUEntities : DbContext
    {
        public DiscoSTUEntities()
            : base("name=DiscoSTUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Disco> Disco { get; set; }
        public virtual DbSet<DiscoTipo> DiscoTipo { get; set; }
        public virtual DbSet<Interprete> Interprete { get; set; }
        public virtual DbSet<Puntuacion> Puntuacion { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
        public virtual DbSet<v_disco> v_disco { get; set; }
        public virtual DbSet<v_tipo> v_tipo { get; set; }
        public virtual DbSet<v_top5> v_top5 { get; set; }
    }
}
