//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disco_STU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_disco
    {
        public int IdDisco { get; set; }
        public int IdTipo { get; set; }
        public string Titulo { get; set; }
        public Nullable<double> Agno { get; set; }
        public string Interprete { get; set; }
    }
}
